// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceStatsUpdate() {
  return window['go']['main']['App']['ForceStatsUpdate']();
}

export function GetChampionBuild(arg1, arg2) {
  return window['go']['main']['App']['GetChampionBuild'](arg1, arg2);
}

export function GetChampionDetails(arg1, arg2) {
  return window['go']['main']['App']['GetChampionDetails'](arg1, arg2);
}

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetGameflowPhase() {
  return window['go']['main']['App']['GetGameflowPhase']();
}

export function GetGoldDiff() {
  return window['go']['main']['App']['GetGoldDiff']();
}

export function GetMetaChampions() {
  return window['go']['main']['App']['GetMetaChampions']();
}

export function GetPersonalStats() {
  return window['go']['main']['App']['GetPersonalStats']();
}

export function RegisterToggleHotkey() {
  return window['go']['main']['App']['RegisterToggleHotkey']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
