// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {lcu} from '../models';

export function ForceStatsUpdate():Promise<string>;

export function GetChampionBuild(arg1:number,arg2:string):Promise<main.ChampionBuildData>;

export function GetChampionDetails(arg1:number,arg2:string):Promise<main.ChampionDetails>;

export function GetConnectionStatus():Promise<Record<string, any>>;

export function GetGameflowPhase():Promise<Record<string, any>>;

export function GetGoldDiff():Promise<Record<string, any>>;

export function GetMetaChampions():Promise<main.MetaData>;

export function GetPersonalStats():Promise<lcu.PersonalStats>;

export function RegisterToggleHotkey():Promise<void>;

export function ToggleWindow():Promise<void>;
